package.path="tools/content-editor/?.lua;runtime/gen1recomp/?.lua;"..package.path
local P=require("Gen3CutscenePreview")
local map={objects={{localId=1,x=4,y=5}}}
local rows={{op="lockall"},{op="message",ptr="hello"},{op="waitbuttonpress"},
  {op="closemessage"},{op="delay",frames=60},
  {op="applymovement",localId=32783,movement={19,17,254}},{op="end"}}
local p=P.new(rows,map,function() return "Hello" end,1)
P.step(p);P.step(p);assert(p.dialogue=="Hello")
p.playing=true;P.step(p);assert(p.waiting and not p.playing)
P.step(p);assert(not p.dialogue)
P.step(p);assert(p.wait==1)
p.playing=true;P.update(p,.2);assert(p.index==5 and p.wait>.79)
P.step(p);assert(p.actors[1].x==5 and p.actors[1].y==4)
assert(map.objects[1].x==4 and rows[6].movement[1]==19)
P.step(p);assert(p.done and not p.playing)
local unsafe=P.new({{op="applymovement",localId=1,movement={19,200,254}}},map,function() end)
P.step(unsafe);assert(not unsafe.error and #unsafe.warnings==1 and unsafe.actors[1].x==4)
local unsupported=P.new({{op="goto",target="loop"}},map,function() end)
P.step(unsupported);assert(not unsupported.error and #unsupported.warnings==1 and unsupported.index==1)
P.step(unsupported);assert(unsupported.done)
local fresh=P.new(rows,map,function() end,1);assert(fresh.index==0 and fresh.actors[1].x==4)
print("PASS: cutscene dialogue, timing, movement, isolation, restart and unsupported commands")
local scripts={root={{op="checkflag",flag=42},{op="goto_if",cond=1,target="enabled"},{op="message",ptr="off"},{op="end"}},
  enabled={{op="call",target="child"},{op="message",ptr="on"},{op="end"}},
  child={{op="setflag",flag=43},{op="return"}}}
local function branch() return P.new(scripts.root,{},function(row) return row.ptr end,nil,function(id) return scripts[id] end,"root") end
local on=branch();P.step(on);assert(on.prompt.id==42 and not on.error)
P.step(on);assert(on.index==1,"Await branch input")
P.answer(on,true);P.step(on);assert(on.script=="enabled")
P.step(on);P.step(on);P.step(on);assert(on.script=="enabled" and on.flags[43])
P.step(on);assert(on.dialogue=="on")
local off=branch();P.step(off);P.answer(off,false);P.step(off);P.step(off);assert(off.dialogue=="off" and not off.flags[43])
local vars=P.new({{op="compare_var_to_value",var=100,value=7},{op="goto_if",cond=1,target="child"}}, {},function() end,nil,function(id) return scripts[id] end)
P.step(vars);assert(vars.prompt.id==100 and vars.index==0)
P.answer(vars,7);P.step(vars);P.step(vars);assert(vars.script=="child")
local loop=P.new({{op="call",target="child"}}, {},function() end,nil,function() return {{op="call",target="child"}} end)
for _=1,70 do P.step(loop) end
assert(not loop.error and #loop.warnings>0)
print("PASS: flag choices, both branches, linked calls/returns, isolated state, variables and recursion bounds")
local fx=P.new({{op="playse",[1]=2},{op="textcolor",color=1},{op="end"}}, {},function() end)
P.step(fx);P.step(fx);P.step(fx);assert(fx.done and not fx.error and fx.notes.playse and fx.notes.textcolor)
local route=P.new({{op="applymovement",localId=1,movement="route"}},map,function() end)
route.movements={route={47,91,19,254}};P.step(route);assert(not route.error and route.actors[1].x==5)
local skipped=P.new({{op="unknown_game_effect"},{op="end"}}, {},function() end)
P.step(skipped);assert(not skipped.prompt and not skipped.error and #skipped.warnings==1)
P.step(skipped);assert(skipped.done)
local Maps=require("Gen3CutsceneMaps")
local source={A={objects={{scriptKey="caller",localId=2,x=3,y=4}}},B={signs={{scriptKey="target"}}}}
local scripts2={caller={{op="call",target="target"}},target={{op="call",target="caller"}}}
local locations=Maps.locations(source,{},scripts2,"target")
assert(#locations==2 and locations[1].actor==2 and locations[1].map=="A")
locations=Maps.locations(source,{A={objects={{scriptKey="other"}}}},scripts2,"target")
assert(#locations==1 and locations[1].map=="B","Project map replaces original bindings")
assert(#Maps.locations(source,{},scripts2,"unattached")==0)
print("PASS: presentation commands, shared routes, explicit skipping, transitive and edited map bindings")
local camera=Maps.camera(80,70,1200,250,{x=40,y=35},3,false)
assert(camera.scale==3 and camera.w<80*16 and camera.h<70*16)
assert(math.abs(camera.x+camera.w/2-40.5*16)<.01)
local edge=Maps.camera(80,70,1200,250,{x=79,y=69},4,false)
assert(edge.x+edge.w<=80*16 and edge.y+edge.h<=70*16)
local overview=Maps.camera(80,70,1200,250,{x=40,y=35},3,true)
assert(overview.scale<1 and math.abs(overview.h-70*16)<.01)
print("PASS: focused zoom, map-edge camera bounds and full-map overview")
local cry=P.new({{op="playmoncry",[1]=25},{op="waitmoncry"},{op="end"}}, {},function() end)
P.step(cry);P.step(cry);P.step(cry);assert(cry.done and not cry.prompt and not cry.error)
assert(cry.notes.playmoncry and cry.notes.waitmoncry)
print("PASS: Pokemon cry and wait commands continue without blocking")
local missing=P.new({{op="applymovement",localId=99,movement={19,254}},{op="message",ptr="after"},{op="end"}},map,function() return "Still playing" end)
missing.playing=true;P.step(missing);assert(missing.playing and not missing.error and not missing.prompt)
P.step(missing);assert(missing.dialogue=="Still playing")
local objects=P.new({{op="removeobject",localId=1},{op="setobjectxy",localId=1,[2]=8,[3]=9},{op="addobject",localId=1}},map,function() end)
P.step(objects);assert(objects.actors[1].hidden)
P.step(objects);P.step(objects);assert(not objects.actors[1].hidden and objects.actors[1].x==8 and map.objects[1].x==4)
print("PASS: missing-actor recovery continues to dialogue; object visibility and position remain isolated")
