-- Serialize editor_project.lua and emit a loadable mod main.lua.

local ModWriter = {}

local function isArray(t)
  if type(t) ~= "table" then return false end
  local n = 0
  for k in pairs(t) do
    if type(k) ~= "number" or k < 1 or k % 1 ~= 0 then return false end
    if k > n then n = k end
  end
  -- LuaJIT # is unreliable on holes (e.g. {[2]=x} may report #=2).
  if n ~= #t then return false end
  for i = 1, n do
    if t[i] == nil then return false end
  end
  return true
end

local function escapeStr(s)
  return string.format("%q", tostring(s))
end

local function writeValue(v, indent, lines)
  indent = indent or 0
  local pad = string.rep("  ", indent)
  local t = type(v)
  if t == "nil" then
    lines[#lines + 1] = "nil"
  elseif t == "boolean" then
    lines[#lines + 1] = v and "true" or "false"
  elseif t == "number" then
    lines[#lines + 1] = tostring(v)
  elseif t == "string" then
    lines[#lines + 1] = escapeStr(v)
  elseif t == "table" then
    if isArray(v) then
      if #v == 0 then
        lines[#lines + 1] = "{}"
        return
      end
      -- compact numeric arrays (blocks) on one line when short enough
      local numeric = true
      for i = 1, #v do
        if type(v[i]) ~= "number" then numeric = false; break end
      end
      if numeric and #v <= 40 then
        local parts = {}
        for i = 1, #v do parts[i] = tostring(v[i]) end
        lines[#lines + 1] = "{ " .. table.concat(parts, ", ") .. " }"
        return
      end
      lines[#lines + 1] = "{"
      for i = 1, #v do
        local chunk = {}
        writeValue(v[i], indent + 1, chunk)
        local inner = table.concat(chunk, "\n")
        if inner:find("\n") then
          lines[#lines + 1] = string.rep("  ", indent + 1) .. inner:gsub("\n", "\n" .. string.rep("  ", indent + 1)) .. ","
        else
          lines[#lines + 1] = string.rep("  ", indent + 1) .. inner .. ","
        end
      end
      lines[#lines + 1] = pad .. "}"
    else
      lines[#lines + 1] = "{"
      local keys = {}
      for k in pairs(v) do keys[#keys + 1] = k end
      table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
      for _, k in ipairs(keys) do
        local key
        if type(k) == "number" then
          key = "[" .. tostring(k) .. "]"
        elseif type(k) == "string" and k:match("^[%a_][%w_]*$") then
          key = k
        else
          key = "[" .. escapeStr(tostring(k)) .. "]"
        end
        local chunk = {}
        writeValue(v[k], indent + 1, chunk)
        local inner = table.concat(chunk, "\n")
        if inner:find("\n") then
          lines[#lines + 1] = string.rep("  ", indent + 1) .. key .. " = " .. inner .. ","
        else
          lines[#lines + 1] = string.rep("  ", indent + 1) .. key .. " = " .. inner .. ","
        end
      end
      lines[#lines + 1] = pad .. "}"
    end
  else
    lines[#lines + 1] = "nil -- unsupported " .. t
  end
end

function ModWriter.serializeProject(project)
  local lines = {
    "-- Auto-generated by the Gen1Recomp content editor.  Edit in the editor",
    "-- or regenerate main.lua via Save.  Do not hand-merge with carelessness.",
    "return ",
  }
  local body = {}
  writeValue(project, 0, body)
  lines[#lines + 1] = table.concat(body, "\n")
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

local function emitTableLiteral(v, indent)
  local lines = {}
  writeValue(v, indent or 1, lines)
  return table.concat(lines, "\n")
end

-- Turn relative asset strings into mod.path joins for runtime loading.
-- NOTE: Lua patterns have no "|"; match assets/ and tilesets/ separately.
local function rewriteModPaths(lit)
  local function rewrite(prefix, rel)
    -- Vanilla ROM cache paths stay game-root relative.
    if rel:sub(1, #"assets/generated/") == "assets/generated/" then
      return prefix .. '"' .. rel .. '"'
    end
    return prefix .. 'mod.path .. "/' .. rel .. '"'
  end
  lit = lit:gsub('(%w+%s*=%s*)"(assets/[^"]+)"', rewrite)
  lit = lit:gsub('(%w+%s*=%s*)"(tilesets/[^"]+)"', rewrite)
  -- Script rows: { "show_image", "assets/foo.png", ... }
  lit = lit:gsub('("show_image"%s*,%s*)"(assets/[^"]+)"', rewrite)
  return lit
end

local EDITOR_ONLY = {
  effectTemplate = true, healAmount = true, statusCures = true,
  ballRandMax = true, ballHpFactor = true, ballWobble = true,
  ballAutoCatch = true, vitaminStat = true, xStat = true,
  ppFull = true, ppAllMoves = true, encounters = true, superRod = true,
  source = true,
}

local function stripEditorFields(rec)
  local out = {}
  for k, v in pairs(rec) do
    if type(k) == "string" and k:sub(1, 1) ~= "_" and not EDITOR_ONLY[k] then
      if v ~= "" then out[k] = v end
    end
  end
  return out
end

-- Only brand-new ids should register.  Missing/_isNew=false → patch.
-- (Old logic defaulted to register, which fails on vanilla ids under api 2
-- and silently drops the whole mod — including accuracy tweaks.)
local function emitVerb(raw)
  return (raw and raw._isNew == true) and "register" or "patch"
end

local function valuesEqual(a, b)
  if a == b then return true end
  if type(a) ~= type(b) then return false end
  if type(a) ~= "table" then return false end
  local na, nb = 0, 0
  for k, v in pairs(a) do
    na = na + 1
    if not valuesEqual(v, b[k]) then return false end
  end
  for _ in pairs(b) do nb = nb + 1 end
  return na == nb
end

-- Patch payload: only fields that differ from the vanilla/base record.
-- Falls back to the full stripped record when no base is available.
local function diffAgainstBase(base, rec)
  if type(base) ~= "table" then return rec end
  local out = {}
  local any = false
  for k, v in pairs(rec) do
    if k ~= "id" and not valuesEqual(v, base[k]) then
      out[k] = v
      any = true
    end
  end
  if not any then return nil end
  return out
end

local function effectIdFor(item)
  return (item.id or "ITEM") .. "_EFFECT"
end

-- Authorable move_effects templates -> register() with a generated run().
local function emitMoveEffectRegister(eff)
  if type(eff) ~= "table" then return nil end
  local eid = eff.id
  if type(eid) ~= "string" or eid == "" then return nil end
  local tmpl = eff.template or "status_side"
  local qeid = string.format("%q", eid)
  local chance = tonumber(eff.chance) or 26
  local status = tostring(eff.status or "BRN")
  local stat = tostring(eff.stat or "attack")
  local delta = tonumber(eff.delta) or 1
  local acc = eff.accuracyChecked ~= false

  if tmpl == "empty" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "full",
  })]], qeid)
  end

  if tmpl == "status_side" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "secondary",
    run = function(ctx)
      local battle, target, move = ctx.battle, ctx.target, ctx.move
      local StatusRegistry = require("src.battle.StatusRegistry")
      local romText = require("src.core.RomText")
      local function displayName(b)
        return b.isPlayer and b.name or ("Enemy " .. b.name)
      end
      if move and move.type == "FIRE" and target.mon.status == "FRZ" then
        target.mon.status = nil
        return { romText(battle.data, "_FireDefrostedText",
          "Fire defrosted\n%%s!", displayName(target)) }
      end
      if battle.rng(0, 255) >= %d then return {} end
      return StatusRegistry.inflict(battle, target, %q, {
        moveType = move and move.type, secondary = true,
        source = move and move.id,
      })
    end,
  })]], qeid, chance, status)
  end

  if tmpl == "flinch_side" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "secondary",
    run = function(ctx)
      local battle, target = ctx.battle, ctx.target
      if target.substituteHP then return {} end
      if battle.rng(0, 255) < %d then target.flinched = true end
      return {}
    end,
  })]], qeid, chance)
  end

  if tmpl == "confuse_side" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "secondary",
    run = function(ctx)
      local battle, target = ctx.battle, ctx.target
      local romText = require("src.core.RomText")
      local function displayName(b)
        return b.isPlayer and b.name or ("Enemy " .. b.name)
      end
      if target.confusedTurns then return {} end
      if battle.rng(0, 255) >= %d then return {} end
      target.confusedTurns = battle.rng(2, 5)
      return { romText(battle.data, "_BecameConfusedText",
        "%%s\nbecame confused!", displayName(target)) }
    end,
  })]], qeid, chance)
  end

  if tmpl == "status_primary" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "primary",
    accuracyChecked = %s,
    run = function(ctx)
      local battle, target, move = ctx.battle, ctx.target, ctx.move
      local StatusRegistry = require("src.battle.StatusRegistry")
      local romText = require("src.core.RomText")
      if target.mon.status then
        return { romText(battle.data, "_ButItFailedText", "But, it failed!") }
      end
      local msgs = StatusRegistry.inflict(battle, target, %q, {
        toxic = move and move.id == "TOXIC",
        moveType = move and move.type,
        source = move and move.id,
      })
      if not msgs or #msgs == 0 then
        return { romText(battle.data, "_ButItFailedText", "But, it failed!") }
      end
      return msgs
    end,
  })]], qeid, acc and "true" or "false", status)
  end

  if tmpl == "stat_up" or tmpl == "stat_down" then
    local sign = (tmpl == "stat_down") and -1 or 1
    local fromEnemy = tmpl == "stat_down"
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "primary",
    accuracyChecked = %s,
    run = function(ctx)
      local MoveEffects = require("src.battle.MoveEffects")
      local who = %s and ctx.target or ctx.user
      return MoveEffects.changeStage(ctx.battle, who, %q, %d, %s)
    end,
  })]], qeid,
      (tmpl == "stat_down" and acc) and "true" or "false",
      fromEnemy and "true" or "false",
      stat, sign * delta, fromEnemy and "true" or "false")
  end

  if tmpl == "stat_down_side" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "secondary",
    run = function(ctx)
      local battle, target = ctx.battle, ctx.target
      local MoveEffects = require("src.battle.MoveEffects")
      if target.substituteHP then return {} end
      if battle.rng(0, 255) >= %d then return {} end
      return MoveEffects.changeStage(battle, target, %q, -%d, false)
    end,
  })]], qeid, chance, stat, delta)
  end

  if tmpl == "recoil" then
    local div = tonumber(eff.recoilDiv) or 4
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "full",
    afterDamage = function(ctx)
      local romText = require("src.core.RomText")
      local function displayName(b)
        return b.isPlayer and b.name or ("Enemy " .. b.name)
      end
      local recoil = math.max(1, math.floor(ctx.rawDamage / %d))
      ctx.say(romText(ctx.battle.data, "_HitWithRecoilText",
        "%%s's\nhit with recoil!", displayName(ctx.user)))
      ctx.battle:applyDamage(ctx.user, recoil)
    end,
  })]], qeid, div)
  end

  if tmpl == "drain" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "full",
    afterDamage = function(ctx)
      local romText = require("src.core.RomText")
      local function displayName(b)
        return b.isPlayer and b.name or ("Enemy " .. b.name)
      end
      ctx.drain()
      ctx.say(romText(ctx.battle.data, "_SuckedHealthText",
        "Sucked health from\n%%s!", displayName(ctx.target)))
    end,
  })]], qeid)
  end

  if tmpl == "ohko" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "full",
    gate = function(ctx)
      local TypeChart = require("src.battle.TypeChart")
      local TurnOrder = require("src.battle.TurnOrder")
      local romText = require("src.core.RomText")
      local function displayName(b)
        return b.isPlayer and b.name or ("Enemy " .. b.name)
      end
      if TypeChart.effectiveness(ctx.move.type, ctx.target.curTypes) == 0 then
        return false, romText(ctx.battle.data, "_DoesntAffectMonText",
          "It doesn't affect\n%%s!", displayName(ctx.target))
      end
      if TurnOrder.effectiveSpeed(ctx.user) < TurnOrder.effectiveSpeed(ctx.target) then
        return false, "But, it failed!"
      end
      return true
    end,
    chooseDamage = function()
      return 65535, { crit = false, typeMult = 10, ohko = true }
    end,
  })]], qeid)
  end

  if tmpl == "multi_hit" then
    local dist = eff.multiHit
    local lit
    if type(dist) == "table" then
      lit = emitTableLiteral(dist, 1)
    else
      lit = tostring(tonumber(dist) or 2)
    end
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "full",
    hitCount = function(ctx)
      local dist = ctx.move.multiHit or %s
      if type(dist) == "number" then return dist end
      return dist[ctx.rng(0, #dist - 1) + 1]
    end,
  })]], qeid, lit)
  end

  if tmpl == "fixed_damage" then
    local dmg = tonumber(eff.fixedDamage) or 40
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "full",
    chooseDamage = function(ctx)
      return %d, { crit = false, typeMult = 10 }
    end,
  })]], qeid, dmg)
  end

  if tmpl == "charge" then
    local inv = eff.semiInvulnerable and true or false
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "full",
    charge = { invulnerable = %s, anim = %q },
  })]], qeid, inv and "true" or "false",
      tostring(eff.chargeAnim or "TELEPORT"))
  end

  if tmpl == "confuse_primary" then
    return string.format([[
  mod.content.move_effects:register(%s, {
    kind = "primary",
    accuracyChecked = %s,
    run = function(ctx)
      local battle, target = ctx.battle, ctx.target
      local romText = require("src.core.RomText")
      local function displayName(b)
        return b.isPlayer and b.name or ("Enemy " .. b.name)
      end
      if target.confusedTurns then
        return { romText(battle.data, "_ButItFailedText", "But, it failed!") }
      end
      target.confusedTurns = battle.rng(2, 5)
      return { romText(battle.data, "_BecameConfusedText",
        "%%s\nbecame confused!", displayName(target)) }
    end,
  })]], qeid, acc and "true" or "false")
  end

  return nil
end

local function emitEffectRegister(item)
  local tmpl = item.effectTemplate or "key"
  local eid = item.effect or effectIdFor(item)
  local qeid = string.format("%q", eid)
  local lines = {}

  if tmpl == "heal" then
    local amt = tonumber(item.healAmount) or 20
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = true,
    use = function(data, save, itemId, target)
      if not target then return "failed", { "No target." } end
      if (target.hp or 0) <= 0 then return "failed", { "It won't have any effect." } end
      local max = target.stats and target.stats.hp or target.hp
      if target.hp >= max then return "failed", { "It won't have any effect." } end
      target.hp = math.min(max, target.hp + %d)
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. " recovered HP." }
    end,
  })]], qeid, amt)

  elseif tmpl == "max_heal" then
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = true,
    use = function(data, save, itemId, target)
      if not target or (target.hp or 0) <= 0 then return "failed", { "It won't have any effect." } end
      local max = target.stats and target.stats.hp or target.hp
      if target.hp >= max then return "failed", { "It won't have any effect." } end
      target.hp = max
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. " recovered HP." }
    end,
  })]], qeid)

  elseif tmpl == "full_restore" then
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = true,
    use = function(data, save, itemId, target)
      if not target or (target.hp or 0) <= 0 then return "failed", { "It won't have any effect." } end
      local max = target.stats and target.stats.hp or target.hp
      local changed = target.hp < max or target.status ~= nil
      if not changed then return "failed", { "It won't have any effect." } end
      target.hp = max
      target.status = nil
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. " recovered HP." }
    end,
  })]], qeid)

  elseif tmpl == "status" then
    local cures = item.statusCures or { "PSN", "BRN", "FRZ", "SLP", "PAR" }
    local set = {}
    for _, s in ipairs(cures) do set[#set + 1] = string.format("[%q] = true", s) end
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = true,
    use = function(data, save, itemId, target)
      if not target or not target.status then return "failed", { "It won't have any effect." } end
      local cures = { %s }
      if not cures[target.status] then return "failed", { "It won't have any effect." } end
      target.status = nil
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. "'s status was cured." }
    end,
  })]], qeid, table.concat(set, ", "))

  elseif tmpl == "revive" or tmpl == "max_revive" then
    local full = tmpl == "max_revive"
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = true,
    use = function(data, save, itemId, target)
      if not target or (target.hp or 0) > 0 then return "failed", { "It won't have any effect." } end
      local max = target.stats and target.stats.hp or 1
      target.hp = %s
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. " was revived." }
    end,
  })]], qeid, full and "max" or "math.max(1, math.floor(max / 2))")

  elseif tmpl == "rare_candy" then
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = false,
    use = function(data, save, itemId, target)
      if not target then return "failed", { "No target." } end
      local lvl = target.level or 1
      if lvl >= 100 then return "failed", { "It won't have any effect." } end
      target.level = lvl + 1
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. " grew to level " .. target.level .. "!" }
    end,
  })]], qeid)

  elseif tmpl == "vitamin" then
    local stat = item.vitaminStat or "hp"
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = false,
    use = function(data, save, itemId, target)
      if not target then return "failed", { "No target." } end
      target.statExp = target.statExp or {}
      local key = %q
      local cur = target.statExp[key] or 0
      if cur >= 25600 then return "failed", { "It won't have any effect." } end
      target.statExp[key] = math.min(25600, cur + 2560)
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. "'s " .. key .. " rose." }
    end,
  })]], qeid, stat)

  elseif tmpl == "pp_restore" then
    local full = item.ppFull and true or false
    local all = item.ppAllMoves and true or false
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = true,
    use = function(data, save, itemId, target, battle, moveIndex)
      if not target or not target.moves then return "failed", { "It won't have any effect." } end
      local function restore(slot)
        if not slot then return false end
        local max = slot.ppMax or slot.pp or 0
        local cur = slot.pp or 0
        if cur >= max then return false end
        if %s then slot.pp = max else slot.pp = math.min(max, cur + 10) end
        return true
      end
      local changed = false
      if %s then
        for _, slot in ipairs(target.moves) do if restore(slot) then changed = true end end
      else
        changed = restore(target.moves[moveIndex or 1])
      end
      if not changed then return "failed", { "It won't have any effect." } end
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. "'s PP was restored." }
    end,
  })]], qeid, full and "true" or "false", all and "true" or "false")

  elseif tmpl == "pp_up" then
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = true, field = true, battle = false,
    use = function(data, save, itemId, target, battle, moveIndex)
      if not target or not target.moves then return "failed", { "It won't have any effect." } end
      local slot = target.moves[moveIndex or 1]
      if not slot then return "failed", { "It won't have any effect." } end
      local ups = slot.ppUps or 0
      if ups >= 3 then return "failed", { "It won't have any effect." } end
      slot.ppUps = ups + 1
      local base = slot.ppMax or slot.pp or 5
      slot.ppMax = math.floor(base * (1 + 0.2 * slot.ppUps) + 0.5)
      local name = target.nickname or (data.pokemon[target.species] and data.pokemon[target.species].name) or "?"
      return "consumed", { name .. "'s PP was raised." }
    end,
  })]], qeid)

  elseif tmpl == "x_item" then
    local stat = item.xStat or "attack"
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    needsTarget = false, field = false, battle = true,
    use = function(data, save, itemId, target, battle)
      if not battle or not battle.player then return "failed", { "It won't have any effect." } end
      battle.player.stages = battle.player.stages or {}
      local key = %q
      local cur = battle.player.stages[key] or 0
      if cur >= 6 then return "failed", { "It won't have any effect." } end
      battle.player.stages[key] = cur + 1
      return "consumed", { "Stat rose." }
    end,
  })]], qeid, stat)

  elseif tmpl == "flute" then
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    field = true, battle = true,
    use = function()
      return "kept", { "Played the POKé FLUTE." }
    end,
  })]], qeid)

  elseif tmpl == "ball" or tmpl == "machine" or tmpl == "stone" or tmpl == "custom" or tmpl == "none" then
    -- ball/machine/stone/custom/none: no generated use(), or custom binds an existing id
    return nil

  elseif tmpl == "key" then
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    field = true, battle = false,
    use = function(data, save, itemId)
      local def = data.items[itemId]
      local n = def and def.name or itemId
      return "kept", { "This is the " .. n .. "." }
    end,
  })]], qeid)

  else
    lines[#lines + 1] = string.format([[
  mod.content.item_effects:register(%s, {
    field = true,
    use = function()
      return "failed", { "It won't have any effect." }
    end,
  })]], qeid)
  end
  return table.concat(lines, "\n")
end

function ModWriter.emitMain(project, baseData)
  baseData = baseData or {}
  -- Seed trainer_headers / trainerClass before maps + headers are emitted.
  ModWriter.ensureTrainerHeaders(project)
  local id = project.id or "content_mod"
  local out = {
    string.format("-- %s: generated by tools/content-editor (do not hand-edit;", id),
    "-- re-Save from the content editor, or maintain editor_project.lua).",
    "return function(mod)",
    "",
  }

  -- palettes (before sprites / pokemon that may reference them)
  local palIds = {}
  for pid in pairs(project.palettes or {}) do palIds[#palIds + 1] = pid end
  table.sort(palIds)
  for _, pid in ipairs(palIds) do
    local raw = project.palettes[pid]
    local colors = raw and (raw.colors or raw)
    if type(colors) == "table" then
      local named, triples = {}, {}
      for i = 1, 4 do
        local c = colors[i] or { 0, 0, 0 }
        local r, g, b
        if c.r then r, g, b = c.r, c.g, c.b
        else r, g, b = c[1] or 0, c[2] or 0, c[3] or 0 end
        named[i] = { r = r, g = g, b = b }
        triples[i] = { r, g, b }
      end
      if raw._isNew == true then
        out[#out + 1] = string.format(
          "  mod.content.palettes:register(%q, { colors = %s })",
          pid, emitTableLiteral(named, 1))
      else
        out[#out + 1] = string.format(
          "  mod.content.palettes:override(%q, %s)",
          pid, emitTableLiteral(triples, 1))
      end
      out[#out + 1] = ""
    end
  end

  -- overworld sprites
  local sprIds = {}
  for sid in pairs(project.sprites or {}) do sprIds[#sprIds + 1] = sid end
  table.sort(sprIds)
  for _, sid in ipairs(sprIds) do
    local raw = project.sprites[sid]
    local rec = stripEditorFields(raw)
    rec.id = rec.id or sid
    local verb = emitVerb(raw)
    local lit = rewriteModPaths(emitTableLiteral(rec, 1))
    out[#out + 1] = string.format("  mod.content.sprites:%s(%q, %s)",
      verb, sid, lit)
    out[#out + 1] = ""
  end

  -- tilesets (maps may reference them)
  local tsIds = {}
  for tid in pairs(project.tilesets or {}) do tsIds[#tsIds + 1] = tid end
  table.sort(tsIds)
  for _, tid in ipairs(tsIds) do
    local raw = project.tilesets[tid]
    local rec = stripEditorFields(raw)
    rec.id = rec.id or tid
    local verb = emitVerb(raw)
    local lit = rewriteModPaths(emitTableLiteral(rec, 1))
    out[#out + 1] = string.format("  mod.content.tilesets:%s(%q, %s)",
      verb, tid, lit)
    out[#out + 1] = ""
  end

  -- types before pokemon/moves so f.id("type_chart") resolves
  local typeIds = {}
  for tid in pairs(project.types or {}) do typeIds[#typeIds + 1] = tid end
  table.sort(typeIds)
  for _, tid in ipairs(typeIds) do
    local raw = project.types[tid]
    local rec = {
      name = raw.name or tid,
      category = raw.category or "special",
    }
    if raw.index ~= nil then rec.index = raw.index end
    out[#out + 1] = string.format(
      "  mod.content.type_chart:register(%q, %s)",
      tid, emitTableLiteral(rec, 1))
    out[#out + 1] = ""
  end
  local matchKeys = {}
  for key in pairs(project.type_matchups or {}) do matchKeys[#matchKeys + 1] = key end
  table.sort(matchKeys)
  for _, key in ipairs(matchKeys) do
    local mult = project.type_matchups[key]
    out[#out + 1] = string.format(
      "  mod.content.type_chart:register(%q, { multiplier = %d })",
      key, tonumber(mult) or 10)
    out[#out + 1] = ""
  end

  local pIds = {}
  for pid in pairs(project.pokemon or {}) do pIds[#pIds + 1] = pid end
  table.sort(pIds)
  for _, pid in ipairs(pIds) do
    local raw = project.pokemon[pid]
    local rec = stripEditorFields(raw)
    rec.id = rec.id or pid
    -- New species need sprite paths for schema; patches keep whatever was
    -- cloned from vanilla (including assets/generated/...).
    if emitVerb(raw) == "register" then
      if not rec.spriteFront or rec.spriteFront == "" then
        rec.spriteFront = "assets/" .. pid:lower() .. "_front.png"
      end
      if not rec.spriteBack or rec.spriteBack == "" then
        rec.spriteBack = "assets/" .. pid:lower() .. "_back.png"
      end
    end
    local verb = emitVerb(raw)
    local lit = rewriteModPaths(emitTableLiteral(rec, 1))
    out[#out + 1] = string.format("  mod.content.pokemon:%s(%q, %s)",
      verb, pid, lit)
    out[#out + 1] = ""
  end

  -- Custom move effects before moves so f.id("move_effects") resolves.
  local meIds = {}
  for eid in pairs(project.moveEffects or {}) do meIds[#meIds + 1] = eid end
  table.sort(meIds)
  for _, eid in ipairs(meIds) do
    local chunk = emitMoveEffectRegister(project.moveEffects[eid])
    if chunk and chunk ~= "" then
      out[#out + 1] = chunk
      out[#out + 1] = ""
    end
  end

  local mvIds = {}
  for mid in pairs(project.moves or {}) do mvIds[#mvIds + 1] = mid end
  table.sort(mvIds)
  local baseMoves = baseData.moves or {}
  for _, mid in ipairs(mvIds) do
    local raw = project.moves[mid]
    local rec = stripEditorFields(raw)
    rec.id = rec.id or mid
    local verb = emitVerb(raw)
    local payload = rec
    local skip = false
    if verb == "patch" then
      local diff = diffAgainstBase(baseMoves[mid], rec)
      if not diff then
        skip = true -- identical to vanilla; no-op
      else
        payload = diff
      end
    end
    if not skip then
      out[#out + 1] = string.format("  mod.content.moves:%s(%q, %s)",
        verb, mid, emitTableLiteral(payload, 1))
      out[#out + 1] = ""
    end
  end

  local baIds = {}
  for bid in pairs(project.battle_anims or {}) do baIds[#baIds + 1] = bid end
  table.sort(baIds)
  for _, bid in ipairs(baIds) do
    local raw = project.battle_anims[bid]
    local rec = stripEditorFields(raw)
    local verb = emitVerb(raw)
    out[#out + 1] = string.format("  mod.content.battle_anims:%s(%q, %s)",
      verb, bid, emitTableLiteral(rec, 1))
    out[#out + 1] = ""
  end

  local iIds = {}
  for iid in pairs(project.items or {}) do iIds[#iIds + 1] = iid end
  table.sort(iIds)
  local NEEDS_TARGET = {
    heal = true, max_heal = true, full_restore = true, status = true,
    revive = true, max_revive = true, vitamin = true, rare_candy = true,
    pp_restore = true, pp_up = true, machine = true, stone = true,
  }
  local EMIT_EFFECT = {
    heal = true, max_heal = true, full_restore = true, status = true,
    revive = true, max_revive = true, vitamin = true, rare_candy = true,
    pp_restore = true, pp_up = true, x_item = true, flute = true, key = true,
  }

  for _, iid in ipairs(iIds) do
    local raw = project.items[iid]
    local tmpl = raw.effectTemplate or (raw._isNew == false and "none" or "heal")
    if tmpl == "ball" then
      local ballId = raw.ball or iid
      out[#out + 1] = string.format([[
  mod.content.balls:register(%q, {
    randMax = %d, hpFactor = %d, wobbleFactor = %d, autoCatch = %s,
    tossAnim = "TOSS_ANIM",
  })]], ballId,
        tonumber(raw.ballRandMax) or 255,
        tonumber(raw.ballHpFactor) or 12,
        tonumber(raw.ballWobble) or 255,
        raw.ballAutoCatch and "true" or "false")
      out[#out + 1] = ""
    elseif EMIT_EFFECT[tmpl] then
      local chunk = emitEffectRegister(raw)
      if chunk and chunk ~= "" then
        out[#out + 1] = chunk
        out[#out + 1] = ""
      end
    end
    local rec = stripEditorFields(raw)
    rec.id = rec.id or iid
    if EMIT_EFFECT[tmpl] or tmpl == "custom" then
      rec.effect = raw.effect or effectIdFor(raw)
    end
    if NEEDS_TARGET[tmpl] then
      rec.needsTarget = true
    end
    if tmpl == "ball" then
      rec.ball = raw.ball or iid
    end
    if tmpl == "key" then
      rec.tossable = false
    end
    if tmpl == "x_item" then
      rec.needsTarget = false
    end
    local verb = emitVerb(raw)
    out[#out + 1] = string.format("  mod.content.items:%s(%q, %s)",
      verb, iid, emitTableLiteral(rec, 1))
    out[#out + 1] = ""
  end

  local mIds = {}
  for mid in pairs(project.maps or {}) do mIds[#mIds + 1] = mid end
  table.sort(mIds)
  for _, mid in ipairs(mIds) do
    local raw = project.maps[mid]
    local rec = stripEditorFields(raw)
    rec.id = rec.id or mid
    local verb = emitVerb(raw)
    out[#out + 1] = string.format("  mod.content.maps:%s(%q, %s)",
      verb, mid, emitTableLiteral(rec, 1))
    out[#out + 1] = ""
    if raw.encounters then
      local everb = emitVerb(raw)
      out[#out + 1] = string.format("  mod.content.encounters:%s(%q, %s)",
        everb, mid, emitTableLiteral(raw.encounters, 1))
      out[#out + 1] = ""
    end
  end

  -- Super Rod groups live under field.superRod[mapId]
  local superRod = {}
  local superRodDelete = {}
  for _, mid in ipairs(mIds) do
    local slots = project.maps[mid] and project.maps[mid].superRod
    if type(slots) == "table" then
      if #slots == 0 then
        superRodDelete[#superRodDelete + 1] = mid
      else
        local clean = {}
        for i, slot in ipairs(slots) do
          clean[i] = { level = slot.level, species = slot.species }
        end
        superRod[mid] = clean
      end
    end
  end
  if next(superRod) then
    out[#out + 1] = string.format(
      "  mod.content.field:patch(%q, %s)",
      "superRod", emitTableLiteral(superRod, 1))
    out[#out + 1] = ""
  end
  table.sort(superRodDelete)
  for _, mid in ipairs(superRodDelete) do
    out[#out + 1] = string.format(
      "  mod.content.field:patch(%q, { [%q] = mod.DELETE })",
      "superRod", mid)
    out[#out + 1] = ""
  end

  -- Old / Good Rod tables (global field.fishing)
  if type(project.fishing) == "table" and next(project.fishing) then
    out[#out + 1] = string.format(
      "  mod.content.field:patch(%q, %s)",
      "fishing", emitTableLiteral(project.fishing, 1))
    out[#out + 1] = ""
  end

  -- text strings (_LABEL -> string); override so vanilla labels replace cleanly
  local textIds = {}
  for tid in pairs(project.text or {}) do textIds[#textIds + 1] = tid end
  table.sort(textIds)
  for _, tid in ipairs(textIds) do
    local body = project.text[tid]
    if type(body) == "string" and body ~= "" then
      out[#out + 1] = string.format("  mod.content.text:override(%q, %s)",
        tid, escapeStr(body))
    end
  end
  if #textIds > 0 then out[#out + 1] = "" end

  -- text_pointers keyed by map label
  local ptrLabels = {}
  for lbl in pairs(project.text_pointers or {}) do ptrLabels[#ptrLabels + 1] = lbl end
  table.sort(ptrLabels)
  for _, lbl in ipairs(ptrLabels) do
    local ptrs = project.text_pointers[lbl]
    if type(ptrs) == "table" and next(ptrs) then
      out[#out + 1] = string.format(
        "  mod.content.text_pointers:patch(%q, %s)",
        lbl, emitTableLiteral(ptrs, 1))
      out[#out + 1] = ""
    end
  end

  -- trainers
  local trIds = {}
  for tid in pairs(project.trainers or {}) do trIds[#trIds + 1] = tid end
  table.sort(trIds)
  for _, tid in ipairs(trIds) do
    local raw = project.trainers[tid]
    local rec = stripEditorFields(raw)
    rec.id = rec.id or tid
    local verb = emitVerb(raw)
    local lit = rewriteModPaths(emitTableLiteral(rec, 1))
    out[#out + 1] = string.format("  mod.content.trainers:%s(%q, %s)",
      verb, tid, lit)
    out[#out + 1] = ""
  end

  -- Special encounters (Encounters tab): synthetic trainers + gift command
  ModWriter.emitSpecialEncounters(project, out)

  -- trainer_headers keyed by map label.
  -- Newer engines expose mod.content.trainer_headers. Older Gen1Recomp still
  -- loads Data.trainer_headers at runtime but has no registry — apply the
  -- same rows on mods.loaded so sight/dialogue/beat flags work there too.
  local thLabels = {}
  for lbl in pairs(project.trainer_headers or {}) do
    thLabels[#thLabels + 1] = lbl
  end
  table.sort(thLabels)
  local thTable = {}
  for _, lbl in ipairs(thLabels) do
    local headers = project.trainer_headers[lbl]
    if type(headers) == "table" and next(headers) then
      local idxs = {}
      for idx in pairs(headers) do
        if type(idx) == "number" and idx > 0 then idxs[#idxs + 1] = idx end
      end
      table.sort(idxs)
      if #idxs > 0 then
        local bucket = {}
        for _, idx in ipairs(idxs) do
          local hdr = headers[idx]
          if type(hdr) == "table" then
            bucket[idx] = stripEditorFields(hdr)
          end
        end
        if next(bucket) then thTable[lbl] = bucket end
      end
    end
  end
  if next(thTable) then
    local lit = emitTableLiteral(thTable, 2)
    out[#out + 1] = "  do"
    out[#out + 1] = "    local _ceTrainerHeaders = " .. lit
    out[#out + 1] = "    if mod.content.trainer_headers then"
    out[#out + 1] = "      for label, bucket in pairs(_ceTrainerHeaders) do"
    -- [0]=DELETE forces dictionary merge (avoids array-concat duplicates).
    out[#out + 1] = "        local patch = { [0] = mod.DELETE }"
    out[#out + 1] = "        for idx, hdr in pairs(bucket) do patch[idx] = hdr end"
    out[#out + 1] = "        mod.content.trainer_headers:patch(label, patch)"
    out[#out + 1] = "      end"
    out[#out + 1] = "    else"
    out[#out + 1] = "      mod.events:on(\"mods.loaded\", function(ev)"
    out[#out + 1] = "        local th = ev.data and ev.data.trainer_headers"
    out[#out + 1] = "        if type(th) ~= \"table\" then return end"
    out[#out + 1] = "        for label, bucket in pairs(_ceTrainerHeaders) do"
    out[#out + 1] = "          local dest = th[label]"
    out[#out + 1] = "          if type(dest) ~= \"table\" then"
    out[#out + 1] = "            dest = {}"
    out[#out + 1] = "            th[label] = dest"
    out[#out + 1] = "          end"
    out[#out + 1] = "          for idx, hdr in pairs(bucket) do"
    out[#out + 1] = "            if type(idx) == \"number\" and type(hdr) == \"table\" then"
    out[#out + 1] = "              dest[idx] = hdr"
    out[#out + 1] = "            end"
    out[#out + 1] = "          end"
    out[#out + 1] = "        end"
    out[#out + 1] = "      end)"
    out[#out + 1] = "    end"
    out[#out + 1] = "  end"
    out[#out + 1] = ""
  end

  -- Compile talkScripts (editor steps) into map_scripts.talk rows, then emit.
  local scripts = ModWriter.compileTalkScripts(project)
  ModWriter.applySpecialEncounterBinds(project, scripts)
  local msIds = {}
  for mid in pairs(scripts) do msIds[#msIds + 1] = mid end
  -- also include any hand-authored project.map_scripts
  for mid in pairs(project.map_scripts or {}) do
    if not scripts[mid] then msIds[#msIds + 1] = mid end
  end
  table.sort(msIds)
  for _, mid in ipairs(msIds) do
    local bundled = scripts[mid] or { talk = {} }
    local hand = project.map_scripts and project.map_scripts[mid]
    if hand and hand.talk then
      bundled.talk = bundled.talk or {}
      for textId, rows in pairs(hand.talk) do
        if not bundled.talk[textId] then
          bundled.talk[textId] = rows
        end
      end
    end
    if bundled.talk and next(bundled.talk) then
      local lit = rewriteModPaths(emitTableLiteral({ talk = bundled.talk }, 1))
      out[#out + 1] = string.format(
        "  mod.content.map_scripts:register(%q, %s)",
        mid, lit)
      out[#out + 1] = ""
    end
  end

  if next(project.eventFlags or {}) then
    out[#out + 1] = "  -- event flags declared in the content editor:"
    local flags = {}
    for name in pairs(project.eventFlags) do flags[#flags + 1] = name end
    table.sort(flags)
    for _, name in ipairs(flags) do
      out[#out + 1] = string.format("  --   %s", name)
    end
    out[#out + 1] = ""
  end

  -- audio: music / cries / sfx / map_songs
  local audio = project.audio or {}
  local function emitAudioBucket(regName, bucket, preferOverride)
    local ids = {}
    for aid in pairs(bucket or {}) do ids[#ids + 1] = aid end
    table.sort(ids)
    for _, aid in ipairs(ids) do
      local val = bucket[aid]
      local lit
      if type(val) == "string" then
        lit = escapeStr(val)
      else
        local clean = stripEditorFields(val)
        lit = rewriteModPaths(emitTableLiteral(clean, 1))
      end
      local verb = preferOverride and "override" or "register"
      if type(val) == "table" and val._isNew == false then
        verb = "override"
      end
      out[#out + 1] = string.format("  mod.content.%s:%s(%q, %s)",
        regName, verb, aid, lit)
      out[#out + 1] = ""
    end
  end
  emitAudioBucket("music", audio.songs, false)
  emitAudioBucket("cries", audio.cries, true)
  emitAudioBucket("sfx", audio.sfx, false)
  emitAudioBucket("map_songs", audio.mapSongs, true)

  -- AI classes
  local aiIds = {}
  for aid in pairs(project.aiClasses or {}) do aiIds[#aiIds + 1] = aid end
  table.sort(aiIds)
  for _, aid in ipairs(aiIds) do
    local raw = project.aiClasses[aid]
    local rec = stripEditorFields(raw)
    if rec.item == "" then rec.item = nil end
    local verb = emitVerb(raw)
    out[#out + 1] = string.format("  mod.content.ai_classes:%s(%q, %s)",
      verb, aid, emitTableLiteral(rec, 1))
    out[#out + 1] = ""
  end

  -- constants (deep patches / overrides for lists)
  local constants = project.constants or {}
  local constKeys = {}
  for k in pairs(constants) do constKeys[#constKeys + 1] = k end
  table.sort(constKeys)
  for _, key in ipairs(constKeys) do
    local val = constants[key]
    if key == "badges" or key == "hmMoves" or key == "encounterBuckets" then
      local lit = emitTableLiteral(val, 1)
      if key == "badges" then lit = rewriteModPaths(lit) end
      out[#out + 1] = string.format(
        "  mod.content.constants:override(%q, %s)",
        key, lit)
    else
      out[#out + 1] = string.format(
        "  mod.content.constants:patch(%q, %s)",
        key, emitTableLiteral(val, 1))
    end
    out[#out + 1] = ""
  end

  -- field.boot (includes boot.screens when set)
  if type(project.boot) == "table" and next(project.boot) then
    out[#out + 1] = string.format(
      "  mod.content.field:patch(%q, %s)",
      "boot", emitTableLiteral(project.boot, 1))
    out[#out + 1] = ""
  end

  -- field.title / intro / theme / townMap (UI tab)
  for _, key in ipairs({ "title", "intro", "theme", "townMap" }) do
    local rec = project[key]
    if type(rec) == "table" and next(rec) then
      local lit = rewriteModPaths(emitTableLiteral(stripEditorFields(rec), 1))
      out[#out + 1] = string.format(
        "  mod.content.field:patch(%q, %s)", key, lit)
      out[#out + 1] = ""
    end
  end

  -- font pages
  local fontIds = {}
  for fid in pairs(project.font or {}) do fontIds[#fontIds + 1] = fid end
  table.sort(fontIds)
  for _, fid in ipairs(fontIds) do
    local raw = project.font[fid]
    if type(raw) == "table" then
      local rec = stripEditorFields(raw)
      local verb = emitVerb(raw)
      local lit = rewriteModPaths(emitTableLiteral(rec, 1))
      out[#out + 1] = string.format("  mod.content.font:%s(%q, %s)",
        verb, fid, lit)
      out[#out + 1] = ""
    end
  end

  -- engine Strings() overrides
  local strIds = {}
  for sid in pairs(project.strings or {}) do strIds[#strIds + 1] = sid end
  table.sort(strIds)
  for _, sid in ipairs(strIds) do
    local body = project.strings[sid]
    if type(body) == "string" and body ~= "" then
      out[#out + 1] = string.format("  mod.content.strings:override(%q, %s)",
        sid, escapeStr(body))
    end
  end
  if #strIds > 0 then out[#out + 1] = "" end

  -- field.playerSprites (walk / bike / surf / fly / surfPikachu remaps)
  if type(project.playerSprites) == "table" then
    local ps = {}
    for k, v in pairs(project.playerSprites) do
      if type(k) == "string" and type(v) == "string" and v ~= "" then
        ps[k] = v
      end
    end
    if next(ps) then
      out[#out + 1] = string.format(
        "  mod.content.field:patch(%q, %s)",
        "playerSprites", emitTableLiteral(ps, 1))
      out[#out + 1] = ""
    end
  end

  -- field.playerPics (battle / trainer-card art paths)
  if type(project.playerPics) == "table" then
    local pp = {}
    for k, v in pairs(project.playerPics) do
      if type(k) == "string" and type(v) == "string" and v ~= "" then
        pp[k] = v
      end
    end
    if next(pp) then
      local lit = rewriteModPaths(emitTableLiteral(pp, 1))
      out[#out + 1] = string.format(
        "  mod.content.field:patch(%q, %s)",
        "playerPics", lit)
      out[#out + 1] = ""
    end
  end

  -- field.ledges (deep-merge lists append; emit only author-added rows)
  if type(project.ledges) == "table" and #project.ledges > 0 then
    local rows = {}
    for _, ledge in ipairs(project.ledges) do
      if type(ledge) == "table" then
        rows[#rows + 1] = stripEditorFields(ledge)
      end
    end
    if #rows > 0 then
      out[#out + 1] = string.format(
        "  mod.content.field:patch(%q, %s)",
        "ledges", emitTableLiteral(rows, 1))
      out[#out + 1] = ""
    end
  end

  -- field.hiddenItems
  if type(project.hiddenItems) == "table" and next(project.hiddenItems) then
    out[#out + 1] = string.format(
      "  mod.content.field:patch(%q, %s)",
      "hiddenItems", emitTableLiteral(project.hiddenItems, 1))
    out[#out + 1] = ""
  end

  -- field.badgeGates (false = suppress / DELETE so deep-merge removes it)
  if type(project.badgeGates) == "table" then
    local gates, gateDelete = {}, {}
    for mid, gate in pairs(project.badgeGates) do
      if gate == false then
        gateDelete[#gateDelete + 1] = mid
      elseif type(gate) == "table" then
        gates[mid] = stripEditorFields(gate)
      end
    end
    if next(gates) then
      out[#out + 1] = string.format(
        "  mod.content.field:patch(%q, %s)",
        "badgeGates", emitTableLiteral(gates, 1))
      out[#out + 1] = ""
    end
    table.sort(gateDelete)
    for _, mid in ipairs(gateDelete) do
      out[#out + 1] = string.format(
        "  mod.content.field:patch(%q, { [%q] = mod.DELETE })",
        "badgeGates", mid)
      out[#out + 1] = ""
    end
  end

  -- Oak's Lab starter remap (pokemon.before_give), same seam as
  -- mods/example_mew_starter.
  local remap = project.starterRemap
  if type(remap) == "table" and next(remap) then
    local has = false
    for _, to in pairs(remap) do
      if type(to) == "table" and to.species and to.species ~= "" then
        has = true; break
      elseif type(to) == "string" and to ~= "" then
        has = true; break
      end
    end
    if has then
      out[#out + 1] = "  do"
      out[#out + 1] = "    local remap = {"
      local keys = {}
      for from in pairs(remap) do keys[#keys + 1] = from end
      table.sort(keys)
      for _, from in ipairs(keys) do
        local to = remap[from]
        local sp, lv
        if type(to) == "table" then
          sp, lv = to.species, tonumber(to.level) or 5
        else
          sp, lv = to, 5
        end
        if sp and sp ~= "" then
          out[#out + 1] = string.format(
            "      [%q] = { species = %q, level = %d },", from, sp, lv)
        end
      end
      out[#out + 1] = "    }"
      out[#out + 1] = "    mod.events:on(\"pokemon.before_give\", function(gift)"
      out[#out + 1] = "      local map = gift.ctx.overworld and gift.ctx.overworld.map"
      out[#out + 1] = "      if not (map and map.id == \"OAKS_LAB\") then return end"
      out[#out + 1] = "      if gift.ctx.save.flags and gift.ctx.save.flags.EVENT_GOT_STARTER then return end"
      out[#out + 1] = "      local hit = remap[gift.species]"
      out[#out + 1] = "      if not hit then return end"
      out[#out + 1] = "      gift.species = hit.species"
      out[#out + 1] = "      gift.level = hit.level"
      out[#out + 1] = "    end)"
      out[#out + 1] = "  end"
      out[#out + 1] = ""
    end
  end

  out[#out + 1] = "end"
  out[#out + 1] = ""
  return table.concat(out, "\n")
end

local function specialTrainerId(specId)
  return "OPP_SPEC_" .. tostring(specId)
end

local function projectMapLabel(project, mapId)
  local m = project.maps and project.maps[mapId]
  if m and type(m.label) == "string" and m.label ~= "" then return m.label end
  if type(mapId) ~= "string" or mapId == "" then return "Map" end
  return (mapId:lower():gsub("_(%w)", function(c) return c:upper() end)
    :gsub("^%w", string.upper))
end

-- Ensure every trainer object has a trainer_headers row, and wire Special
-- battle encounters (bind TEXT_*) as real overworld trainers (trainerClass +
-- headers).  Without headers, engageTrainer has no beat flag / won text.
function ModWriter.ensureTrainerHeaders(project)
  if type(project) ~= "table" then return end
  local State = require("State")
  project.trainer_headers = project.trainer_headers or {}
  project.text = project.text or {}
  project.eventFlags = project.eventFlags or {}

  for mapId, map in pairs(project.maps or {}) do
    if type(map) == "table" then
      local label = projectMapLabel(project, mapId)
      for i, obj in ipairs(map.objects or {}) do
        if type(obj) == "table" and obj.trainerClass and obj.trainerClass ~= "" then
          local idx = obj.index or i
          project.trainer_headers[label] = project.trainer_headers[label] or {}
          local bucket = project.trainer_headers[label]
          if type(bucket[idx]) ~= "table" then
            local base = "_" .. mapId .. "Trainer" .. idx
            local beat = State.modFlag(project, "BEAT_" .. mapId .. "_" .. idx)
            project.eventFlags[beat] = true
            bucket[idx] = {
              range = 2,
              battle = base .. "Battle",
              won = base .. "Won",
              after = base .. "After",
              event = beat,
              opponent = obj.trainerClass,
              party = tonumber(obj.trainerParty) or 1,
            }
            project.text[base .. "Battle"] = project.text[base .. "Battle"]
              or "Let's fight!"
            project.text[base .. "Won"] = project.text[base .. "Won"] or "I lost..."
            project.text[base .. "After"] = project.text[base .. "After"]
              or "You're strong."
          else
            bucket[idx].opponent = obj.trainerClass
            bucket[idx].party = tonumber(obj.trainerParty)
              or bucket[idx].party or 1
          end
        end
      end
    end
  end

  for sid, spec in pairs(project.specialEncounters or {}) do
    if type(spec) == "table"
        and (spec.kind or "gift") == "battle"
        and type(spec.mapId) == "string" and spec.mapId ~= ""
        and type(spec.bindTextId) == "string" and spec.bindTextId ~= "" then
      local map = project.maps and project.maps[spec.mapId]
      if type(map) == "table" then
        for i, obj in ipairs(map.objects or {}) do
          if type(obj) == "table" and obj.text == spec.bindTextId then
            local idx = obj.index or i
            local tid = specialTrainerId(sid)
            local label = projectMapLabel(project, spec.mapId)
            local base = "_" .. spec.mapId .. "Trainer" .. idx
            local beat = State.modFlag(project,
              (spec.flag and spec.flag ~= "" and spec.flag)
                or ("BEAT_" .. sid))
            project.eventFlags[beat] = true
            obj.trainerClass = tid
            obj.trainerParty = 1
            project.text[base .. "Battle"] = spec.text or "Let's fight!"
            project.text[base .. "Won"] = spec.won or "I lost..."
            project.text[base .. "After"] = spec.after or "You're strong."
            project.trainer_headers[label] = project.trainer_headers[label] or {}
            project.trainer_headers[label][idx] = {
              range = tonumber(spec.range) or 2,
              battle = base .. "Battle",
              won = base .. "Won",
              after = base .. "After",
              event = beat,
              opponent = tid,
              party = 1,
            }
          end
        end
      end
    end
  end
end

local function specialMonSlot(spec)
  local slot = {
    species = spec.species or "MAGIKARP",
    level = tonumber(spec.level) or 5,
  }
  if type(spec.moves) == "table" and #spec.moves > 0 then
    local moves = {}
    for i = 1, math.min(4, #spec.moves) do
      local mid = spec.moves[i]
      if type(mid) == "string" and mid ~= "" then
        moves[#moves + 1] = mid
      end
    end
    if #moves > 0 then slot.moves = moves end
  end
  if type(spec.dvs) == "table" then
    local dvs, any = {}, false
    for _, k in ipairs({ "attack", "defense", "speed", "special", "hp" }) do
      local n = tonumber(spec.dvs[k])
      if n ~= nil then
        dvs[k] = math.max(0, math.min(15, math.floor(n)))
        any = true
      end
    end
    if any then slot.dvs = dvs end
  end
  return slot
end

-- Emit OPP_SPEC_* trainers and mod:give_special for Encounters-tab specials.
function ModWriter.emitSpecialEncounters(project, out)
  local specs = project.specialEncounters
  if type(specs) ~= "table" or not next(specs) then return end

  local ids = {}
  for sid in pairs(specs) do ids[#ids + 1] = sid end
  table.sort(ids)

  local gifts = {}
  for _, sid in ipairs(ids) do
    local spec = specs[sid]
    if type(spec) == "table" then
      if (spec.kind or "gift") == "battle" then
        local tid = specialTrainerId(sid)
        local mon = specialMonSlot(spec)
        local rec = {
          id = tid,
          name = (spec.name and spec.name ~= "" and spec.name)
            or (spec.species or sid),
          baseMoney = 0,
          parties = { { mon } },
        }
        out[#out + 1] = string.format(
          "  mod.content.trainers:register(%q, %s)",
          tid, emitTableLiteral(rec, 1))
        out[#out + 1] = ""
      else
        gifts[#gifts + 1] = sid
      end
    end
  end

  if #gifts == 0 then return end

  out[#out + 1] = "  -- Special gift encounters (Encounters tab)"
  out[#out + 1] = "  local SPECIALS = {"
  for _, sid in ipairs(gifts) do
    local spec = specs[sid]
    local entry = {
      species = spec.species or "MAGIKARP",
      level = tonumber(spec.level) or 5,
    }
    if type(spec.moves) == "table" and #spec.moves > 0 then
      entry.moves = {}
      for i = 1, math.min(4, #spec.moves) do
        local mid = spec.moves[i]
        if type(mid) == "string" and mid ~= "" then
          entry.moves[#entry.moves + 1] = mid
        end
      end
    end
    if type(spec.dvs) == "table" then
      entry.dvs = {}
      for _, k in ipairs({ "attack", "defense", "speed", "special", "hp" }) do
        if spec.dvs[k] ~= nil then
          entry.dvs[k] = tonumber(spec.dvs[k]) or 0
        end
      end
    end
    out[#out + 1] = string.format("    [%q] = %s,",
      sid, emitTableLiteral(entry, 2))
  end
  out[#out + 1] = "  }"

  local cmd = (project.id or "content_mod") .. ":give_special"
  out[#out + 1] = string.format(
    "  mod.content.commands:register(%q, {", cmd)
  out[#out + 1] = "    foreground = true,"
  out[#out + 1] = "    fn = function(ctx, specialId)"
  out[#out + 1] = "      local spec = SPECIALS[specialId]"
  out[#out + 1] = "      if not spec then return end"
  out[#out + 1] = "      local Pokemon = require(\"src.pokemon.Pokemon\")"
  out[#out + 1] = "      local Stats = require(\"src.pokemon.Stats\")"
  out[#out + 1] = "      local Party = require(\"src.pokemon.Party\")"
  out[#out + 1] = "      local Boxes = require(\"src.pokemon.Boxes\")"
  out[#out + 1] = "      local BattleState = require(\"src.battle.BattleState\")"
  out[#out + 1] = "      local mon = Pokemon.new(ctx.game.data, spec.species, spec.level)"
  out[#out + 1] = "      if type(spec.dvs) == \"table\" then"
  out[#out + 1] = "        local dvs = {"
  out[#out + 1] = "          attack = tonumber(spec.dvs.attack) or 0,"
  out[#out + 1] = "          defense = tonumber(spec.dvs.defense) or 0,"
  out[#out + 1] = "          speed = tonumber(spec.dvs.speed) or 0,"
  out[#out + 1] = "          special = tonumber(spec.dvs.special) or 0,"
  out[#out + 1] = "        }"
  out[#out + 1] = "        if spec.dvs.hp ~= nil then"
  out[#out + 1] = "          dvs.hp = tonumber(spec.dvs.hp) or 0"
  out[#out + 1] = "        else"
  out[#out + 1] = "          dvs.hp = (dvs.attack % 2) * 8 + (dvs.defense % 2) * 4"
  out[#out + 1] = "            + (dvs.speed % 2) * 2 + (dvs.special % 2)"
  out[#out + 1] = "        end"
  out[#out + 1] = "        mon.dvs = dvs"
  out[#out + 1] = "        mon.stats = Stats.calc(ctx.game.data.pokemon[spec.species],"
  out[#out + 1] = "          spec.level, dvs, mon.statExp)"
  out[#out + 1] = "        mon.hp = mon.stats.hp"
  out[#out + 1] = "      end"
  out[#out + 1] = "      if type(spec.moves) == \"table\" then"
  out[#out + 1] = "        mon.moves = {}"
  out[#out + 1] = "        for _, moveId in ipairs(spec.moves) do"
  out[#out + 1] = "          local mdef = ctx.game.data.moves[moveId]"
  out[#out + 1] = "          mon.moves[#mon.moves + 1] = {"
  out[#out + 1] = "            id = moveId, pp = mdef and mdef.pp or 0,"
  out[#out + 1] = "          }"
  out[#out + 1] = "        end"
  out[#out + 1] = "      end"
  out[#out + 1] = "      local def = ctx.game.data.pokemon[spec.species]"
  out[#out + 1] = "      ctx.game.stringBuffer = (def and def.name) or spec.species"
  out[#out + 1] = "      ctx.pendingPokemonName = spec.species"
  out[#out + 1] = "      BattleState.stampOT(ctx.save, mon)"
  out[#out + 1] = "      local addedToParty = Party.add(ctx.save.party, mon)"
  out[#out + 1] = "      local boxNum = nil"
  out[#out + 1] = "      if not addedToParty then"
  out[#out + 1] = "        boxNum = Boxes.deposit(ctx.save, mon)"
  out[#out + 1] = "        if not boxNum then ctx.lastCheck = false; return end"
  out[#out + 1] = "      end"
  out[#out + 1] = "      local dex = ctx.save.pokedex"
  out[#out + 1] = "      if dex then"
  out[#out + 1] = "        dex.seen[spec.species] = true"
  out[#out + 1] = "        dex.owned[spec.species] = true"
  out[#out + 1] = "      end"
  out[#out + 1] = "      ctx.lastCheck = true"
  out[#out + 1] = "      ctx.addedToParty = addedToParty"
  out[#out + 1] = "      ctx.boxNum = boxNum"
  out[#out + 1] = "      if boxNum and ctx.runner then"
  out[#out + 1] = "        local name = mon.nickname"
  out[#out + 1] = "          or (def and def.name) or spec.species"
  out[#out + 1] = "        ctx.game.boxMonNicks = name"
  out[#out + 1] = "        ctx.game.stringBuffer = tostring(boxNum)"
  out[#out + 1] = "        local Commands = require(\"src.script.Commands\")"
  out[#out + 1] = "        Commands.show_text(ctx, \"_SentToBoxText\")"
  out[#out + 1] = "      end"
  out[#out + 1] = "    end,"
  out[#out + 1] = "  })"
  out[#out + 1] = ""
end

-- Wire bindTextId specials into compiled map talk scripts (oneshot gift/battle).
function ModWriter.applySpecialEncounterBinds(project, scripts)
  local specs = project.specialEncounters
  if type(specs) ~= "table" or not next(specs) then return end
  local State = require("State")
  local cmd = (project.id or "content_mod") .. ":give_special"
  local ids = {}
  for sid in pairs(specs) do ids[#ids + 1] = sid end
  table.sort(ids)
  for _, sid in ipairs(ids) do
    local spec = specs[sid]
    local mapId = type(spec) == "table" and spec.mapId
    local textId = type(spec) == "table" and spec.bindTextId
    if type(spec) == "table"
        and type(mapId) == "string" and mapId ~= ""
        and type(textId) == "string" and textId ~= "" then
      local unique = spec.unique ~= false
      local done = State.modFlag(project, (spec.flag and spec.flag ~= "" and spec.flag)
        or ((spec.kind == "battle") and ("BEAT_" .. sid) or ("GOT_" .. sid)))

      -- Battle + Bind text on a map object: headers/trainerClass already
      -- wired by ensureTrainerHeaders.  A talk script would suppress sight
      -- (checkTrainerSight skips NPCs with talkScript) and is unnecessary
      -- because engageTrainer runs on interact.
      local wiredBattle = false
      if (spec.kind or "gift") == "battle" then
        local map = project.maps and project.maps[mapId]
        local wantClass = specialTrainerId(sid)
        if type(map) == "table" then
          for _, obj in ipairs(map.objects or {}) do
            if type(obj) == "table" and obj.text == textId
                and obj.trainerClass == wantClass then
              wiredBattle = true
              break
            end
          end
        end
      end
      if wiredBattle then
        if scripts[mapId] and scripts[mapId].talk then
          scripts[mapId].talk[textId] = nil
        end
      else
        local rows = {}
        if (spec.kind or "gift") == "battle" then
          local cls = specialTrainerId(sid)
          local before = spec.text or "Let's fight!"
          local won = spec.won or "I lost..."
          local after = spec.after or "You're strong."
          rows[#rows + 1] = { "face_player" }
          if unique then
            rows[#rows + 1] = { "check_flag", done }
            rows[#rows + 1] = { "jump_if_true", "after_fight" }
          end
          rows[#rows + 1] = { "show_text", before }
          rows[#rows + 1] = { "start_battle", "trainer", cls, 1 }
          rows[#rows + 1] = { "jump_if_false", "end" }
          rows[#rows + 1] = { "show_text", won }
          if unique then
            rows[#rows + 1] = { "set_flag", done }
          end
          rows[#rows + 1] = { "jump", "end" }
          if unique then
            rows[#rows + 1] = { "label", "after_fight" }
            rows[#rows + 1] = { "show_text", after }
          end
        else
          local intro = spec.text or "Here! Take this POKeMON!"
          local after = spec.after or "I already gave you one."
          if unique then
            rows[#rows + 1] = { "check_flag", done }
            rows[#rows + 1] = { "jump_if_true", "after_mon" }
          end
          rows[#rows + 1] = { "show_text", intro }
          rows[#rows + 1] = { cmd, sid }
          if unique then
            rows[#rows + 1] = { "set_flag", done }
            rows[#rows + 1] = { "jump", "end" }
            rows[#rows + 1] = { "label", "after_mon" }
            rows[#rows + 1] = { "show_text", after }
          end
        end
        rows[#rows + 1] = { "label", "end" }
        rows = ModWriter.relabelNumericJumps(rows)
        scripts[mapId] = scripts[mapId] or { talk = {} }
        scripts[mapId].talk[textId] = rows
      end
    end
  end
end

-- Convert editor step lists into ScriptRunner command rows.
function ModWriter.compileTalkScripts(project)
  local byMap = {}
  for key, script in pairs(project.talkScripts or {}) do
    local mapId = script.mapId or key:match("^([^/]+)/")
    local textId = script.textId or key:match("/(.+)$")
    if mapId and textId and type(script.steps) == "table" then
      local rows = ModWriter.stepsToRows(project, script.steps)
      if #rows > 0 then
        byMap[mapId] = byMap[mapId] or { talk = {} }
        byMap[mapId].talk[textId] = rows
      end
    end
  end
  return byMap
end

function ModWriter.stepsToRows(project, steps)
  local rows = {}
  local function flagName(short)
    local State = require("State")
    return State.modFlag(project, short)
  end

  for _, step in ipairs(steps) do
    local kind = step.kind or "show_text"
    if kind == "raw" then
      local row = step.row
      if type(step.note) == "string" and step.note:match("%S") then
        row = ModWriter.parseEngineLine(step.note)
      end
      if type(row) == "table" and row[1] then
        local copy = {}
        for i, v in ipairs(row) do copy[i] = v end
        rows[#rows + 1] = copy
      end
    elseif kind == "show_image" then
      local path = step.path or step.image or ""
      if path ~= "" then
        if step.text and step.text ~= "" then
          rows[#rows + 1] = { "show_image", path, step.text }
        else
          rows[#rows + 1] = { "show_image", path }
        end
      end
    elseif kind == "show_text" or kind == "show_label" then
      local t = step.text or step.label or ""
      if t ~= "" then rows[#rows + 1] = { "show_text", t } end
    elseif kind == "ask" then
      local t = step.text or "OK?"
      rows[#rows + 1] = { "ask", t }
      if step.skipOnNo ~= false then
        rows[#rows + 1] = { "jump_if_false", "end" }
      end
    elseif kind == "label" then
      local name = step.name or step.label or "label"
      if name ~= "" then rows[#rows + 1] = { "label", name } end
    elseif kind == "jump" then
      local name = step.name or step.label or "end"
      rows[#rows + 1] = { "jump", name }
    elseif kind == "jump_if_yes" then
      local name = step.name or step.label or "end"
      rows[#rows + 1] = { "jump_if_true", name }
    elseif kind == "jump_if_no" then
      local name = step.name or step.label or "end"
      rows[#rows + 1] = { "jump_if_false", name }
    elseif kind == "face_player" then
      rows[#rows + 1] = { "face_player" }
    elseif kind == "heal_party" then
      rows[#rows + 1] = { "heal_party" }
    elseif kind == "set_flag" then
      rows[#rows + 1] = { "set_flag", flagName(step.flag or "FLAG") }
    elseif kind == "clear_flag" then
      rows[#rows + 1] = { "clear_flag", flagName(step.flag or "FLAG") }
    elseif kind == "check_flag_skip" then
      rows[#rows + 1] = { "check_flag", flagName(step.flag or "FLAG") }
      rows[#rows + 1] = { "jump_if_true", "end" }
    elseif kind == "check_flag_missing" then
      rows[#rows + 1] = { "check_flag", flagName(step.flag or "FLAG") }
      rows[#rows + 1] = { "jump_if_false", "end" }
    elseif kind == "give_item" then
      rows[#rows + 1] = {
        "give_item", step.item or "POTION", tonumber(step.count) or 1,
      }
    elseif kind == "take_item" then
      rows[#rows + 1] = {
        "take_item", step.item or "POTION", tonumber(step.count) or 1,
      }
    elseif kind == "check_item_skip" then
      rows[#rows + 1] = { "check_item", step.item or "POTION" }
      rows[#rows + 1] = { "jump_if_true", "end" }
    elseif kind == "check_item_missing" then
      rows[#rows + 1] = { "check_item", step.item or "POTION" }
      rows[#rows + 1] = { "jump_if_false", "end" }
    elseif kind == "give_pokemon" then
      local sp = step.species or "PIKACHU"
      local lv = tonumber(step.level) or 5
      if step.skipNickname then
        rows[#rows + 1] = { "give_pokemon", sp, lv, true }
      else
        rows[#rows + 1] = { "give_pokemon", sp, lv }
      end
    elseif kind == "give_starter" then
      -- Gift + vanilla starter flag (and optional rival index 1/2/3).
      local sp = step.species or "BULBASAUR"
      local lv = tonumber(step.level) or 5
      if step.text and step.text ~= "" then
        rows[#rows + 1] = { "show_text", step.text }
      end
      if step.skipNickname then
        rows[#rows + 1] = { "give_pokemon", sp, lv, true }
      else
        rows[#rows + 1] = { "give_pokemon", sp, lv }
      end
      rows[#rows + 1] = { "set_flag", "EVENT_GOT_STARTER" }
      if step.choseFlag and step.choseFlag ~= "" then
        rows[#rows + 1] = { "set_flag", flagName(step.choseFlag) }
      end
      local rival = tonumber(step.rivalStarter)
      if rival and rival >= 1 and rival <= 3 then
        rows[#rows + 1] = { "set_field", "rivalStarter", rival }
      end
    elseif kind == "give_money" then
      rows[#rows + 1] = { "give_money", tonumber(step.amount) or 500 }
    elseif kind == "warp" then
      rows[#rows + 1] = {
        "warp",
        step.map or "PALLET_TOWN",
        tonumber(step.x) or 0,
        tonumber(step.y) or 0,
        step.facing or "down",
      }
    elseif kind == "wild_battle" then
      rows[#rows + 1] = {
        "start_battle", "wild",
        step.species or "PIDGEY", tonumber(step.level) or 5,
      }
    elseif kind == "trainer_battle" then
      if step.text and step.text ~= "" then
        rows[#rows + 1] = { "show_text", step.text }
      end
      rows[#rows + 1] = {
        "start_battle", "trainer",
        step.trainer or "OPP_BUG_CATCHER", tonumber(step.party) or 1,
      }
      if step.won and step.won ~= "" then
        rows[#rows + 1] = { "jump_if_false", "end" }
        rows[#rows + 1] = { "show_text", step.won }
      end
    elseif kind == "oneshot_trainer" then
      local done = flagName(step.flag or "BEAT_TRAINER")
      local before = step.text or "Let's fight!"
      local won = step.won or "I lost..."
      local after = step.after or "You're strong."
      local cls = step.trainer or "OPP_BUG_CATCHER"
      local party = tonumber(step.party) or 1
      rows[#rows + 1] = { "face_player" }
      rows[#rows + 1] = { "check_flag", done }
      rows[#rows + 1] = { "jump_if_true", "after_fight" }
      rows[#rows + 1] = { "show_text", before }
      rows[#rows + 1] = { "start_battle", "trainer", cls, party }
      rows[#rows + 1] = { "jump_if_false", "end" }
      rows[#rows + 1] = { "show_text", won }
      rows[#rows + 1] = { "set_flag", done }
      rows[#rows + 1] = { "jump", "end" }
      rows[#rows + 1] = { "label", "after_fight" }
      rows[#rows + 1] = { "show_text", after }
    elseif kind == "set_field" then
      local key = step.field or "mod:value"
      local val = step.value
      if step.valueType == "number" then
        val = tonumber(val) or 0
      elseif step.valueType == "bool" then
        val = (tostring(val) == "true" or val == true)
      end
      rows[#rows + 1] = { "set_field", key, val }
    elseif kind == "oneshot_gift" then
      local done = flagName(step.flag or "DONE")
      local intro = step.text or "Here you go!"
      local after = step.after or "I already gave you one."
      local item = step.item or "POTION"
      rows[#rows + 1] = { "check_flag", done }
      rows[#rows + 1] = { "jump_if_true", "after" }
      rows[#rows + 1] = { "show_text", intro }
      rows[#rows + 1] = { "give_item", item, tonumber(step.count) or 1 }
      rows[#rows + 1] = { "set_flag", done }
      rows[#rows + 1] = { "jump", "end" }
      rows[#rows + 1] = { "label", "after" }
      rows[#rows + 1] = { "show_text", after }
    elseif kind == "oneshot_pokemon" then
      local done = flagName(step.flag or "GOT_MON")
      local intro = step.text or "Here! Take this POKeMON!"
      local after = step.after or "I already gave you one."
      local sp = step.species or "EEVEE"
      local lv = tonumber(step.level) or 25
      rows[#rows + 1] = { "check_flag", done }
      rows[#rows + 1] = { "jump_if_true", "after_mon" }
      rows[#rows + 1] = { "show_text", intro }
      if step.skipNickname then
        rows[#rows + 1] = { "give_pokemon", sp, lv, true }
      else
        rows[#rows + 1] = { "give_pokemon", sp, lv }
      end
      rows[#rows + 1] = { "set_flag", done }
      rows[#rows + 1] = { "jump", "end" }
      rows[#rows + 1] = { "label", "after_mon" }
      rows[#rows + 1] = { "show_text", after }
    end
  end
  -- Avoid duplicating a trailing end label already present from decompile.
  local last = rows[#rows]
  if not (last and last[1] == "label" and last[2] == "end") then
    rows[#rows + 1] = { "label", "end" }
  end
  -- Vanilla ports use numeric jump targets (row indices).  Cloning through
  -- the editor stringifies them ("22"), which fails validation — rewrite
  -- digit targets into real labels before emit.
  return ModWriter.relabelNumericJumps(rows)
end

-- Turn numeric / digit-string jump targets into { "label", "_row_N" } anchors
-- so ScriptRunner.validate accepts editor-emitted talk scripts.
function ModWriter.relabelNumericJumps(rows)
  if type(rows) ~= "table" then return rows end
  local function jumpNum(t)
    if type(t) == "number" and t % 1 == 0 then return t end
    if type(t) == "string" and t:match("^%d+$") then return tonumber(t) end
    return nil
  end
  local src = {}
  for i, row in ipairs(rows) do
    if type(row) == "table" then
      local c = {}
      for j = 1, #row do c[j] = row[j] end
      src[i] = c
    else
      src[i] = row
    end
  end
  local targets = {}
  for _, row in ipairs(src) do
    if type(row) == "table" then
      local v = row[1]
      if v == "jump" or v == "jump_if_true" or v == "jump_if_false" then
        local n = jumpNum(row[2])
        if n and n >= 1 and n <= #src then targets[n] = true end
      end
    end
  end
  if not next(targets) then return src end
  local function labelName(n) return ("_row_%d"):format(n) end
  local out = {}
  for i, row in ipairs(src) do
    if targets[i] then
      out[#out + 1] = { "label", labelName(i) }
    end
    out[#out + 1] = row
  end
  for _, row in ipairs(out) do
    if type(row) == "table" then
      local v = row[1]
      if v == "jump" or v == "jump_if_true" or v == "jump_if_false" then
        local n = jumpNum(row[2])
        if n and targets[n] then row[2] = labelName(n) end
      end
    end
  end
  return out
end

-- Tokenize an "Engine cmd" line into a ScriptRunner row.
-- Supports words, numbers, booleans, "quoted strings", and {table} literals.
function ModWriter.parseEngineLine(line)
  line = tostring(line or ""):gsub("^%s+", ""):gsub("%s+$", "")
  if line == "" then return { "wait", 0 } end
  local parts = {}
  local i, n = 1, #line
  while i <= n do
    local c = line:sub(i, i)
    if c:match("%s") then
      i = i + 1
    elseif c == '"' or c == "'" then
      local q, j, buf = c, i + 1, {}
      while j <= n do
        local ch = line:sub(j, j)
        if ch == "\\" and j < n then
          buf[#buf + 1] = line:sub(j + 1, j + 1)
          j = j + 2
        elseif ch == q then
          j = j + 1
          break
        else
          buf[#buf + 1] = ch
          j = j + 1
        end
      end
      parts[#parts + 1] = table.concat(buf)
      i = j
    elseif c == "{" then
      local depth, j = 1, i + 1
      while j <= n and depth > 0 do
        local ch = line:sub(j, j)
        if ch == "{" then depth = depth + 1
        elseif ch == "}" then depth = depth - 1 end
        j = j + 1
      end
      local chunk = line:sub(i, j - 1)
      local ok, val = pcall(function()
        return assert(load("return " .. chunk, "=engine_cmd"))()
      end)
      parts[#parts + 1] = ok and val or chunk
      i = j
    else
      local j = i
      while j <= n and not line:sub(j, j):match("%s") do j = j + 1 end
      local tok = line:sub(i, j - 1)
      if tok == "true" then parts[#parts + 1] = true
      elseif tok == "false" then parts[#parts + 1] = false
      elseif tonumber(tok) then parts[#parts + 1] = tonumber(tok)
      else parts[#parts + 1] = tok end
      i = j
    end
  end
  if #parts == 0 then return { "wait", 0 } end
  return parts
end

local function formatEngineValue(v, depth, bareOk)
  depth = (depth or 0) + 1
  if depth > 4 then return "{...}" end
  local tv = type(v)
  if tv == "string" then
    -- Bare identifiers only for top-level script args (verb, FLAG, SPECIES).
    -- Inside {tables} always quote so load() round-trips.
    if bareOk and v:match("^[%w_]+$") then return v end
    return string.format("%q", v)
  elseif tv == "number" or tv == "boolean" then
    return tostring(v)
  elseif tv == "table" then
    local bits, n = {}, #v
    for i = 1, n do bits[#bits + 1] = formatEngineValue(v[i], depth, false) end
    local keys = {}
    for k in pairs(v) do
      if not (type(k) == "number" and k >= 1 and k <= n and k % 1 == 0) then
        keys[#keys + 1] = k
      end
    end
    table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
    for _, k in ipairs(keys) do
      local key = (type(k) == "string" and k:match("^[%a_][%w_]*$"))
        and k or ("[" .. formatEngineValue(k, depth, false) .. "]")
      bits[#bits + 1] = key .. " = " .. formatEngineValue(v[k], depth, false)
    end
    return "{ " .. table.concat(bits, ", ") .. " }"
  end
  return "nil"
end

function ModWriter.formatEngineLine(row)
  if type(row) ~= "table" then return tostring(row or "") end
  local parts = {}
  for i = 1, #row do
    parts[i] = formatEngineValue(row[i], 0, true)
  end
  return table.concat(parts, " ")
end

-- Inverse of stepsToRows for browsing vanilla / mod ScriptRunner rows.
-- Recognizes common editor pairings; unknown verbs become raw steps.
function ModWriter.rowsToSteps(rows)
  local steps = {}
  if type(rows) ~= "table" then return steps end
  rows = ModWriter.relabelNumericJumps(rows)

  local function shortFlag(name)
    name = tostring(name or "")
    return name:gsub("^MOD_[^_]+_", "")
  end

  local function pushRaw(row)
    local copy = {}
    for i = 1, #row do copy[i] = row[i] end
    steps[#steps + 1] = {
      kind = "raw",
      note = ModWriter.formatEngineLine(copy),
      row = copy,
    }
  end

  local i = 1
  while i <= #rows do
    local row = rows[i]
    if type(row) == "function" then
      steps[#steps + 1] = { kind = "raw", note = "(inline Lua)" }
      i = i + 1
    elseif type(row) ~= "table" or row[1] == nil then
      i = i + 1
    else
      local verb = row[1]
      local n1 = rows[i + 1]
      local paired = type(n1) == "table" and n1[1]

      if verb == "show_image" then
        steps[#steps + 1] = {
          kind = "show_image",
          path = tostring(row[2] or ""),
          text = (type(row[3]) == "string" and row[3]) or "",
        }
        i = i + 1
      elseif verb == "show_text" then
        steps[#steps + 1] = { kind = "show_text", text = tostring(row[2] or "") }
        i = i + 1
      elseif verb == "ask" then
        local step = { kind = "ask", text = tostring(row[2] or "OK?"), skipOnNo = false }
        if paired == "jump_if_false" and (n1[2] == "end" or n1[2] == nil) then
          step.skipOnNo = true
          i = i + 2
        else
          i = i + 1
        end
        steps[#steps + 1] = step
      elseif verb == "label" then
        -- Skip synthetic trailing end unless it's mid-script.
        if row[2] == "end" and i == #rows then
          i = i + 1
        else
          steps[#steps + 1] = { kind = "label", name = tostring(row[2] or "label") }
          i = i + 1
        end
      elseif verb == "jump" then
        steps[#steps + 1] = { kind = "jump", name = tostring(row[2] or "end") }
        i = i + 1
      elseif verb == "jump_if_true" then
        steps[#steps + 1] = { kind = "jump_if_yes", name = tostring(row[2] or "end") }
        i = i + 1
      elseif verb == "jump_if_false" then
        steps[#steps + 1] = { kind = "jump_if_no", name = tostring(row[2] or "end") }
        i = i + 1
      elseif verb == "face_player" then
        steps[#steps + 1] = { kind = "face_player" }
        i = i + 1
      elseif verb == "heal_party" then
        steps[#steps + 1] = { kind = "heal_party" }
        i = i + 1
      elseif verb == "set_flag" then
        steps[#steps + 1] = { kind = "set_flag", flag = shortFlag(row[2]) }
        i = i + 1
      elseif verb == "clear_flag" then
        steps[#steps + 1] = { kind = "clear_flag", flag = shortFlag(row[2]) }
        i = i + 1
      elseif verb == "check_flag" and paired == "jump_if_true" and n1[2] == "end" then
        steps[#steps + 1] = { kind = "check_flag_skip", flag = shortFlag(row[2]) }
        i = i + 2
      elseif verb == "check_flag" and paired == "jump_if_false" and n1[2] == "end" then
        steps[#steps + 1] = { kind = "check_flag_missing", flag = shortFlag(row[2]) }
        i = i + 2
      elseif verb == "check_item" and paired == "jump_if_true" and n1[2] == "end" then
        steps[#steps + 1] = { kind = "check_item_skip", item = tostring(row[2] or "POTION") }
        i = i + 2
      elseif verb == "check_item" and paired == "jump_if_false" and n1[2] == "end" then
        steps[#steps + 1] = {
          kind = "check_item_missing", item = tostring(row[2] or "POTION"),
        }
        i = i + 2
      elseif verb == "give_item" then
        steps[#steps + 1] = {
          kind = "give_item",
          item = tostring(row[2] or "POTION"),
          count = tonumber(row[3]) or 1,
        }
        i = i + 1
      elseif verb == "take_item" then
        steps[#steps + 1] = {
          kind = "take_item",
          item = tostring(row[2] or "POTION"),
          count = tonumber(row[3]) or 1,
        }
        i = i + 1
      elseif verb == "give_pokemon" then
        steps[#steps + 1] = {
          kind = "give_pokemon",
          species = tostring(row[2] or "PIKACHU"),
          level = tonumber(row[3]) or 5,
          skipNickname = row[4] and true or nil,
        }
        i = i + 1
      elseif verb == "give_money" then
        steps[#steps + 1] = { kind = "give_money", amount = tonumber(row[2]) or 500 }
        i = i + 1
      elseif verb == "warp" then
        steps[#steps + 1] = {
          kind = "warp",
          map = tostring(row[2] or "PALLET_TOWN"),
          x = tonumber(row[3]) or 0,
          y = tonumber(row[4]) or 0,
          facing = tostring(row[5] or "down"),
        }
        i = i + 1
      elseif verb == "start_battle" and row[2] == "wild" then
        steps[#steps + 1] = {
          kind = "wild_battle",
          species = tostring(row[3] or "PIDGEY"),
          level = tonumber(row[4]) or 5,
        }
        i = i + 1
      elseif verb == "start_battle" and row[2] == "trainer" then
        steps[#steps + 1] = {
          kind = "trainer_battle",
          trainer = tostring(row[3] or "OPP_BUG_CATCHER"),
          party = tonumber(row[4]) or 1,
        }
        i = i + 1
      elseif verb == "set_field" then
        local val = row[3]
        local vt = "str"
        if type(val) == "number" then vt = "number"
        elseif type(val) == "boolean" then vt = "bool" end
        steps[#steps + 1] = {
          kind = "set_field",
          field = tostring(row[2] or "mod:value"),
          value = tostring(val == nil and "" or val),
          valueType = vt,
        }
        i = i + 1
      else
        pushRaw(row)
        i = i + 1
      end
    end
  end
  return steps
end

return ModWriter
