return function(game)
  local U = require("tests.drivers.util")
  local root = os.getenv("EDITOR_TEST_ROOT") .. "/tests/content-editor/emerald-playtest/"
  local function report(s)
    local f=assert(io.open(root.."results.log", "a")); f:write(s,"\n"); f:close()
  end
  local function shot(name)
    game.capturePath=root..name..".png"
    for i=1,300 do U.wait(1); if not game.capturePath then break end end
    assert(not game.capturePath, "capture timed out")
  end
  U.wait(5)
  assert(game.mods.order[1]=="emerald_e2e", "mod not loaded")
  assert(#game.mods.errors==0, table.concat(game.mods.errors,"\n"))
  report("PASS: emerald_e2e loaded without errors")
  local hp=require("src.mods.Gen3Compat").pokemonRecord("TREECKO").baseStats.hp
  assert(hp==77, "TREECKO hp is "..tostring(hp))
  report("PASS: TREECKO base HP is 77 in game")
  game:_handleBootAction({action="new_game", name="E2E"})
  U.wait(180)
  assert(game.phase=="field", "field failed")
  shot("new-game")
  report("PASS: new game reached the field")
  local Map = require("src.core.game3.map")
  local Player = require("src.core.game3.player")
  Map.load(nil, game, "EM_LITTLEROOT_TOWN", {x=10,y=10,facing="down"})
  U.wait(90)
  shot("littleroot")
  local x,y=Player.px,Player.py
  U.hold(game,"down",30); U.wait(30)
  assert(Player.px~=x or Player.py~=y, "player did not walk")
  report("PASS: modded Littleroot Town loaded and player walked")
  local credits=require("src.ui.game3.rse.gba_machine").new():manifest("data/generated/gba/credits_rse/manifest.lua")
  assert(credits.pages[2][3].text=="E2E Tester", "credits page 2 is "..tostring(credits.pages[2][3].text))
  report("PASS: edited Emerald credits reached the game")
  local bag=assert(require("src.ui.game3.rse.scene_kit").image("data/generated/gba/rse/bag/bg.png"),"bag background missing")
  local canvas=love.graphics.newCanvas(bag:getDimensions())
  love.graphics.push("all");love.graphics.setCanvas(canvas);love.graphics.clear(0,0,0,0);love.graphics.draw(bag);love.graphics.pop()
  local r,g,b=canvas:newImageData():getPixel(0,0)
  assert(r>.9 and g<.1 and b<.1,"bag background is not the mod's image")
  report("PASS: replaced Emerald bag image reached the game")
  local welcome=require("src.core.game3.rom_text").plain("gText_Birch_Welcome")
  assert(tostring(welcome):find("E2E welcome",1,true),"Birch welcome is "..tostring(welcome))
  report("PASS: edited Birch dialogue reached the game")
  local treecko=require("src.mods.Gen3Compat").pokemonRecord("TREECKO").index
  local entry=require("src.ui.game3.rse.mapsec").readLua("pokemon/pokedex/entries.lua")[treecko]
  assert(entry.category=="E2E KIND" and entry.description=="E2E dex line\nsecond line","Treecko Pokédex entry is "..tostring(entry.category).." / "..tostring(entry.description))
  report("PASS: edited Treecko Pokédex category and description reached the game")
  local mudkip=require("src.mods.Gen3Compat").pokemonRecord("MUDKIP").index
  assert(require("src.ui.game3.rse.starter_choose").species(nil,0)==mudkip,"Birch's bag slot 1 is not Mudkip")
  local sess=require("src.core.game3.rse.init").session()
  require("src.core.game3.scripting.natives_field_rse").giveStarter(nil,0,sess)
  local mon=sess.party[#sess.party]
  assert(mon.species==mudkip and mon.level==12 and mon.nickname=="E2E","starter is "..tostring(mon.species).." lv"..tostring(mon.level).." "..tostring(mon.nickname))
  report("PASS: edited Emerald starter (Mudkip Lv 12 E2E) reached the game")
  local RseMap=require("src.ui.game3.rse.region_map")
  local fly=RseMap.show({session=sess,mode="fly"})
  assert(RseMap.mapSecType(fly,7)==RseMap.TYPE.CITY_CANFLY,"Petalburg is not flyable")
  assert(RseMap.mapSecType(fly,8)==RseMap.TYPE.CITY_CANTFLY,"unvisited Slateport became flyable")
  local dest=RseMap.flyWarpDestination(sess,7,0)
  assert(dest and dest.map=="EM_OLDALE_TOWN" and dest.x==6 and dest.y==17,"Petalburg lands at "..tostring(dest and dest.map))
  for _,icon in ipairs(fly.flyIcons) do if icon.sec==7 then assert(icon.flicker and icon.frame<=3,"Petalburg icon is not shown as flyable") end end
  RseMap.reset()
  report("PASS: edited Emerald Fly destination (Petalburg to Oldale) reached the game")
  Map.load(nil, game, "EM_E2E_COPY", {x=6,y=17,facing="down"})
  U.wait(90)
  assert(Map.current=="EM_E2E_COPY","new map is "..tostring(Map.current))
  shot("new-map")
  x,y=Player.px,Player.py
  U.hold(game,"down",30); U.wait(30)
  assert(Player.px~=x or Player.py~=y, "player did not walk on the new map")
  report("PASS: new EM_ map loaded and player walked")
  assert(#game.mods.errors==0,table.concat(game.mods.errors,"\n"))
  report("COMPLETE")
  love.event.quit()
end
